### ISSUE TITLE
The Resnet_SupCLR.pth is not fit for the net architecture! Please upload a .pth file that can be used~

### ISSUE THREAD

**Issue by Anyway2022** [silvia1993/HyMOS#4]

**Comment by Jing--Li** [comment]
"
Loaded model from pretrained/resnet50_SupCLR.pth
Missing keys: ['simclr_layer.0.weight', 'simclr_layer.0.bias', 'simclr_layer.2.weight', 'simclr_layer.2.bias']
Unexpected keys: ['fc.weight', 'fc.bias']
"

**Comment by Anyway2022** [comment]
"
Loaded model from pretrained/resnet50_SupCLR.pth
Missing keys: ['simclr_layer.0.weight', 'simclr_layer.0.bias', 'simclr_layer.2.weight', 'simclr_layer.2.bias']
Unexpected keys: ['fc.weight', 'fc.bias']
"

**Comment by silvia1993** [comment]
Hello @Anyway2022,

since the resnet50 network pretrained on SupCLR is provided only in TensorFlow we convert it in PyTorch using this tool: [https://github.com/google-research/simclr#model-convertion-to-pytorch-format](https://github.com/google-research/simclr#model-convertion-to-pytorch-format).

Anyway, in the README.md file, we also provide the link to directly download the converted version of it: 
[https://drive.google.com/file/d/1w-IdsYwCScbHTlCUDGCDxCPhY9VH6hRl/view](https://drive.google.com/file/d/1w-IdsYwCScbHTlCUDGCDxCPhY9VH6hRl/view)

Hope this helps!
Silvia

**Comment by Jing--Li** [comment]
Thank you for your reply.
Yes, I did download the converted version you provide through the second link above. It is this converted version that doesn't fit into the net architecture defined by your code. Directly loading the resnet50_SupCLR.pth results in the missing keys and unexpected keys errors as I added as a comment. Please give it a try, use the resnet50_SupCLR.pth file and the code you provided.

**Comment by Anyway2022** [comment]
Thank you for your reply.
Yes, I did download the converted version you provided through the second link above. This converted version doesn't fit into the net architecture defined by your code. Directly loading the resnet50_SupCLR.pth results in the missing keys and unexpected keys errors. Please give it a try; use the resnet50_SupCLR.pth file and the code you provided.

**Comment by silvia1993** [comment]
This is just a warning due to the fact that:

1)  Unexpected keys: ['fc.weight', 'fc.bias'] -> we don't use the last fully connected layer used by SupCLR for the classification
2)  Missing keys: ['simclr_layer.0.weight', 'simclr_layer.0.bias', 'simclr_layer.2.weight', 'simclr_layer.2.bias'] ->  the contrastive head that we use it's not present in the SupCLR architecture

So you can continue the training ignoring this.

**Comment by Anyway2022** [comment]
Thank you for being so patient in answering my questions！Good Luck~
